name: OWOLF
favicon: null
layout_spectrum: 0.35479654371738434
typography_spectrum: 0.7650392174255103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8d785b'
    - '#5a4937'
    - '#e1e4df'
    - '#c5bfa5'
    - '#281b15'
  brandStrength: 0.5868268948979676
  lightness: 0.6203253862913698
  saturation: 0.4508403593208641
  rhythmicContrast: 0.747010022867471
purpose: []
